### ISSUE TITLE
[ERROR] Error in request: struct.unpack( struct.error: unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by deepesh-agarwal** [blacklanternsecurity/TREVORproxy#10]
When trying to use the test command below after starting TREVORProxy:

`curl -6 --proxy socks5://127.0.0.1:1080 icanhasip.com
`
I receive this error:
`curl: (6) Could not resolve host: icanhasip.com
`
And, TREVORProxy says:

```
trevorproxy subnet -s xxxx:xxxx:xxx::/64 -i enp2s0f0
[DEBUG] ip route add local 2604:6280:107::/64 dev enp2s0f0
[INFO] Listening on socks5://127.0.0.1:1080
[DEBUG] Accepting connection from 127.0.0.1:58354
[ERROR] Error in request: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/trevorproxy/lib/socks.py", line 55, in handle
    version, cmd, _, address_type = struct.unpack(
struct.error: unpack requires a buffer of 4 bytes
```

When using this ```curl --proxy socks5://127.0.0.1:1080 -6 api64.ipify.org```
It gets stuck at and no results are received, failing with ```curl: (7) Failed to receive SOCKS5 connect request ack.```:

```
[DEBUG] Accepting connection from 127.0.0.1:37006
[DEBUG] Address type == IPv6
[DEBUG] Destination address: 2607:f2d8:1:3c::3
[DEBUG] AddressFamily.AF_INET6 matches address family (10), randomizing source address
[INFO] Using random source address: xxxx:xxxx:xxx:0:caca:f713:cb72:xxxx
[ERROR] Error in reply: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/trevorproxy/lib/socks.py", line 139, in handle
    remote.connect((address, port))
TimeoutError: [Errno 110] Connection timed out

^X^C[DEBUG] ip route del local 2604:6280:107::/64 dev enp2s0f0
[ERROR] Interrupted
```

Am I missing something here?

**Comment by deepesh-agarwal** [comment]
This was a IPV6 config issue.
