### ISSUE TITLE
TypeError in ssh.py

### ISSUE THREAD

**Issue by dopamin3rgic** [blacklanternsecurity/TREVORproxy#4]
I keep getting this error when running trevorspray/trevorproxy using ssh. 

```
Traceback (most recent call last):                                                                         
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner                                    
    self.run()                                                                                             
  File "/usr/lib/python3.9/threading.py", line 910, in run                                                 
    self._target(*self._args, **self._kwargs)                                                              
  File "/home/kali/.local/lib/python3.9/site-packages/sh.py", line 1683, in wrap                           
    fn(*rgs, **kwargs)                                                                                     
  File "/home/kali/.local/lib/python3.9/site-packages/sh.py", line 2688, in output_thread                  
    done = f.read()                                                                                        
  File "/home/kali/.local/lib/python3.9/site-packages/sh.py", line 3177, in read                           
    self.write_chunk(chunk)                                                                                
  File "/home/kali/.local/lib/python3.9/site-packages/sh.py", line 3154, in write_chunk                    
    self.should_quit = self.process_chunk(chunk)                                                           
  File "/home/kali/.local/lib/python3.9/site-packages/sh.py", line 3063, in process                        
    return handler(chunk)                                                                                  
  File "/home/kali/.local/lib/python3.9/site-packages/sh.py", line 1766, in fn
    return handler(chunk, *a)
  File "/home/kali/.local/lib/python3.9/site-packages/trevorproxy/lib/ssh.py", line 84, in _enter_password
    self._ssh_stdout += char
TypeError: can only concatenate str (not "bytes") to str

```

For the record I am using SSH Key authentication, not password

**Comment by TheTechromancer** [comment]
Thanks for the report. This is fixed in https://github.com/blacklanternsecurity/TREVORproxy/commit/908f348cace3e3ef1d9134efe7af89a03828ba69.
