### ISSUE TITLE
TypeError in ssh.py

### ISSUE THREAD

**Issue by samari-k** [blacklanternsecurity/TREVORproxy#9]
Using trevorspray with `--ssh` on  python 3.12 raises the following error:

```
[ERRR] Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/trevorspray/cli.py", line 285, in main
    sprayer = TrevorSpray(options)
              ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/trevorspray/lib/trevor.py", line 58, in __init__
    proxy = ProxyThread(
            ^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/trevorspray/lib/proxy.py", line 66, in __init__
    self.proxy.start()
  File "/usr/lib/python3.12/site-packages/trevorproxy/lib/ssh.py", line 49, in start
    self.command = b" ".join(self.sh.cmd)
                   ^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected a bytes-like object, str found
```

Changing the lines 49 and 98 in lib/ssh.py fixed it for me. Here is the diff:

```diff
49c49
<             self.command = b" ".join(self.sh.cmd).decode()
---
>             self.command = " ".join(self.sh.cmd).encode()
98c98
<             log.debug(f'Waiting for {" ".join([x.decode() for x in self.sh.cmd])}')
---
>             log.debug(f'Waiting for {" ".join([x for x in self.sh.cmd])}')
```

**Comment by samari-k** [comment]
This only seems to be an issue when installing via the BlackArch repository / pacman. No problem though when installing with pipx.
